### ISSUE TITLE
Error al cerrar aplicación con "Ctrl + C"

### ISSUE THREAD

**Issue by LAS1819** [LAS1819/OW_Nodejs_Express#1]
Me he encontrado con un error inusual a la hora de cerrar la aplicación. Una vez ejecutado el programa, y resuelto las funcionalidades, se queda la sesión abierta. Y ademas, cuando pulso "Ctrl + C" para cerrar la conexión, me salta un error que no comprendo.

![imagen](https://user-images.githubusercontent.com/49163934/81595207-5fe4f380-93c2-11ea-9885-43246f1f227a.png)

Estoy en un sistema operativo de Windows 10, y creo que el error viene cuando instalo Babel, ya que he tenido muchos problemas con los _slash_ ('/'), porque en Windows parecía que necesitaba el _slash_ invertido que usa el sistema ('\'), pero en los vídeos del curso de OpenWebinars no se centran en este aspecto para nada y te dejan con 'el culo al aire' para que busques por internet.

A ver si puedes ayudarme, Pedro.

Lluís Aracil Sabater

**Comment by pedroprieto** [comment]
Buenas,

No entiendo bien el problema. He intentado ejecutar la aplicación pero no me funciona bien. He corregido los slash pero sigue sin ir. ¿Puedes dejarla como la tenías?

En principio no deben afectar los slash, ya que el programa se ejecuta bajo npm con `npm run start`. A partir de ahí node toma el control y debería interpretarlo bien.

Sube los cambios y abre el issue de nuevo cuando lo tengas.

**Comment by LAS1819** [comment]
Perdona, @pedroprieto , no sé cómo explicarme mejor. El programa a mí si que me funciona, pero se me queda abierto:

![imagen](https://user-images.githubusercontent.com/49163934/81670924-a4b36d80-9448-11ea-8699-acffeaaa5d7c.png)

Cuando en el curso conforme hace un 'npm run start sample.txt' y elige una opción, automáticamente se le cierra el programa.

Entonces, la única manera que tengo de acabar con el programa es darle a 'Ctrl + C', y es cuando me salta ese error que te mostraba en el anterior mensaje.

Al principio, estaba usando la consola de windows, y me daba muchos problemas con los slash, pero luego cambié a Git Bash y ya no tenía problemas hasta que me apareció este error que comento...

**Comment by LAS1819** [comment]
Creo que los problemas provienen del archivo 'package.json', que tuve que sacarle las comillas al babel-register y darle la vuelta a los slash... no sé si lo has probado también.
![imagen](https://user-images.githubusercontent.com/49163934/81672122-fad4e080-9449-11ea-8a29-3e52b7129f52.png)

**Comment by pedroprieto** [comment]
Buenas,

Tras cambiar las barras funciona correctamente:
![imagen](https://user-images.githubusercontent.com/7632447/81673962-bf87e100-944c-11ea-9f01-3e1dccddfead.png)

Líneas:
```
"start": "node --require babel-register src/index.js",
"lint": "standard 'src/*.js'"
```

**Comment by LAS1819** [comment]
Nada, @pedroprieto, he hecho los cambios que me has comentado y sigue quedándoseme el programa abierto y he de salir mediante 'ctrl + c'. Lo que me hace suponer que es un error o a la hora de declarar las veriones que uso o un fallo por falta de algo por instalar, pero como ya te digo, en OpenWebinars se saltan muchas instalaciones, como en este curso, que hay un video que se llama 'Instalación' que se supone que va a enseñarte como se instala npm y cómo configurar los archivos, pero de repente saltan a otro vídeo con archivos en el repositorio que no se sabe de dónde han salido, así que cuando me encuentro esas cosas he de pasar a YouTube o Google para encontrar la solución...

De todas maneras, gracias Pedro, seguiré intentándolo a ver si saco dónde está el problema.

**Comment by pedroprieto** [comment]
Ni idea... Supongo que instalas las dependencias con `npm install`, claro...

Prueba a poner escrituras de consola en distintos puntos (al final del proceso, por ejemplo,...) para ver donde se queda colgado exactamente.

**Comment by LAS1819** [comment]
No quiero molestar Pedro, ahora miro lo de las escrituras de consola en distintos puntos, pero he probado de nuevo a instalar 'npm' con 'npm install' y me aparece esto (que lo vi en su momento pero la verdad que no le hice caso):

![imagen](https://user-images.githubusercontent.com/49163934/81680697-c9f9a900-9453-11ea-9c55-e58230788f01.png)

No conozco fund en Git, pero supongo que es como fundir o fusionar, ¿puede que esté ahí el fallo?. Voy a ver de qué trata lo de 'fund' en Git.

**Comment by LAS1819** [comment]
Mira, en el debug.log que me salta, puedo ver que a partir de la línea 11 el 'lifecycle' me da error, y es justo el error que me marca desde la consola, como se ve en las capturas anteriores. Parece con Babel y las comillas o los slash, no sé... ¿Puedes ver algo en claro ahí?

[2020-05-12T11_33_59_667Z-debug.log](https://github.com/LAS1819/OW_Nodejs_Express/files/4615295/2020-05-12T11_33_59_667Z-debug.log)

Saludos y gracias!

**Comment by LAS1819** [comment]
Nada, acabo de pasar el problema. No podía hacer algunas cosas desde CMD de Windows y cambié el código que te dije sustituyendo slash cerradas por abiertas. Luego pasé al Git Bash, y estaba ejecutando el programa desde allí.... todo bien hasta que llegué a esta parte. Pero hoy he pensado... voy a probar el PowerShell de windows... y tachán:

![imagen](https://user-images.githubusercontent.com/49163934/81685545-63c35500-9458-11ea-9fc2-3cb7c39bc327.png)

Muchas gracias por la ayuda Pedro, me has animado a seguir probando cosas. Te dejo tranquilo ya.

Un saludo!! :)

**Comment by pedroprieto** [comment]
Sin problema, Lluis!! Me alegro de que lo hayas sacado. Debe ser una chorrada de Windows...

En cuanto al `npm fund`, como tú bien dices, es de npm, no de git. Tiene que ver con donaciones. Te informa de qué paquetes están buscando financiación, por si quieres contribuir.

Un saludo!!
